nameOverride: ""
fullnameOverride: ""

image:
  repository: redis
  tag: "7.2.5"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 6379
  annotations: {}
  labels: {}

resources: {}

nodeSelector: {}
affinity: {}
tolerations: []

configmap:
  enabled: false
  name: ""
  annotations: {}
  data: {}

auth:
  enabled: false
  existingSecret: ""
  passwordKey: "redis-password"
  password: ""

persistence:
  enabled: false
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

