architecture: standalone

auth:
  enabled: true
  password: "${REDIS_PASSWORD}"

master:
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 500m

service:
  type: ClusterIP
  port: 6379

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
