apiVersion: v1
kind: Service
metadata:
  name: {{ include "jedox-redis.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "jedox-redis.name" . }}
    helm.sh/chart: {{ include "jedox-redis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "jedox-redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

